<?php

namespace App\Faker\Provider;

use Faker\Provider\Base;

class StoneProvider extends Base
{
    public const STONES = [
        'Agate',
        'Agate blanche',
        'Agate bleue',
        'Agate en camée',
        'Agate rose',
        'Agate rubanée',
        'Agate verte',
        'Ambre',
        'Améthyste',
        'Amétrine',
        'Ammolite',
        'Aventurine',
        'Aventurine bleue',
        'Aventurine verte',
        'Azurite',
        'Azurite Malachite',
        'Béryl',
        'Bronzite',
        'Calcédoine',
        'Calcite miel',
        'Calcite verte',
        'Carborandite',
        'Chrysocolle',
        'Chrysoprase',
        'Chrysoprase citron',
        'Citrine',
        'Citrine chauffée',
        'Cornaline bandée',
        'Crisal aqua aura',
        'Cristal de roche',
        'Cristal de roche à inclusion de tourmaline noire',
        'Cristal de roche avec inclusion de rutile',
        'Cristal fumé',
        'Cyanite bleue',
        'Cyanite verte',
        'Diamant d\'Herkimer',
        'Dioptase',
        'Fluorite',
        'Fluorine jaune',
        'Fuschite',
        'Galène',
        'Grenat almadin',
        'Grenat rhodolite',
        'Jaspe sanguine ( ou jaspe Héolitrope )',
        'Howlite',
        'Iolite',
        'Iris',
        'Jade vert',
        'Jade blanc',
        'Jade noir',
        'Jaspe breschia',
        'Jaspe paysage',
        'Jaspe polychrome',
        'Jaspe rouge',
        'Jaspe zébré',
        'Kunzite rose',
        'Kunzite verte',
        'Labradorite',
        'Lapis-lazuli',
        'Larimar',
        'Larme d\'apache',
        'Lépidolite',
        'Malachite',
        'Moldavite',
        'Obsidienne dorée',
        'Obsidienne œil céleste',
        'Œil de chat',
        'Œil de faucon',
        'Œil de fer',
        'Œil de taureau',
        'Œil-de-tigre',
        'Onyx',
        'Opale',
        'Pierre de lune',
        'Pierre de soleil',
        'Prehnite',
        'Pyrite',
        'Pyromorphite',
        'Quartz blanc',
        'Quartz rose',
        'Quartz vert',
        'Serpentine',
        'Sodalite',
        'Shungite',
        'Stibine',
        'Turquoise',
        'Tanzanite',
        'Tourmaline',
        'Tourmaline melon d\'eau',
        'Tourmaline rose',
        'Tourmaline noire brute',
        'Vanadinite',
        'Wulfénite',
        'Zircon',
        'Diamant',
        'Émeraude',
        'Rubis',
        'Saphir',
    ];

    public function stoneName()
    {
        return self::STONES[\random_int(0, \count(self::STONES) - 1)];
    }
}
